### ISSUE TITLE
No gpu devices was detected

### ISSUE THREAD

**Issue by Arsen4ik** [nanopool/nanominer#2]
Hi! My vega 64 don't work with nanominer .
Radeon Software Version
18.12.3
![image](https://user-images.githubusercontent.com/46644855/51083871-f5d91300-16d5-11e9-91e1-bf266a6bddc7.png)

**Comment by Grumpy-Dwarf** [comment]
What is output of `clinfo` command on your system? Does it show AMD Vega card among other OpenCL devices?

**Comment by Ouzelot** [comment]
I have the same problem with my GTX 650, even though I have the latest driver.

**Comment by Grumpy-Dwarf** [comment]
There are lots of reasons for GPU devices to be invisible for miner. For AMD we need to check `clinfo` command output for GPU devices available. For Nvidia there is `nvidia-smi` in `C:\Program Files\NVIDIA Corporation\NVSMI`.
Please provide the output of `clinfo` for AMD case or output of `nvidia-smi` for Nvidia case so we can investigate the problem.

**Comment by Grumpy-Dwarf** [comment]
We've reproduced and fixed AMD devices detection issue in latest nanominer v1.0.7 release, hope this fixes the issue. Thanks for reporting.

**Comment by falantar** [comment]
I have the same problem with my RX 580's. It works fine when I have my monitor plugged into my onboard video, but when i reboot the machine without a monitor plugged and teamviewer in, i get this same error.

**Comment by cbarryb** [comment]
I have same problem.  I have GEFORCE GTX 1070Ti GPUs, but get same error.  Updated drivers and rebooted, buy still no bueno.  

Suggestions?

**Comment by Grumpy-Dwarf** [comment]
> I have same problem. I have GEFORCE GTX 1070Ti GPUs, but get same error. Updated drivers and rebooted, buy still no bueno.
> 
> Suggestions?

Do you have SLI enabled like in this issue https://github.com/FinMiner/FinMiner/issues/7 ?

**Comment by entinio** [comment]
Same problem with my NV rig. SLI is disabled.

```
root@RIG3:~/qkc/nanominer-linux-1.2.2# ./nanominer
                                   _
 _ __   __ _ _ __   ___  _ __ ___ (_)_ __   ___ _ __
| '_ \ / _` | '_ \ / _ \| '_ ` _ \| | '_ \ / _ \ '__|
| | | | (_| | | | | (_) | | | | | | | | | |  __/ |
|_| |_|\__,_|_| |_|\___/|_| |_| |_|_|_| |_|\___|_|

Version 1.2.2
Detected 0 devices
(...)
2019-04-25 23:07:17: No GPU devices were detected, exiting.

root@RIG3:~/qkc/nanominer-linux-1.2.2# nvidia-smi
Thu Apr 25 23:11:29 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:01:00.0  On |                  N/A |
|100%   32C    P0    61W / 220W |     25MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 00000000:02:00.0 Off |                  N/A |
|100%   29C    P0    61W / 220W |      9MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  On   | 00000000:03:00.0 Off |                  N/A |
|100%   32C    P0    64W / 220W |      9MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  On   | 00000000:05:00.0 Off |                  N/A |
|100%   32C    P0    61W / 220W |      9MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  On   | 00000000:06:00.0 Off |                  N/A |
|100%   31C    P0    60W / 220W |      9MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  On   | 00000000:07:00.0 Off |                  N/A |
|100%   30C    P0    60W / 220W |      9MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  On   | 00000000:08:00.0 Off |                  N/A |
|100%   29C    P0    60W / 220W |      9MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by szkotzky** [comment]
Can anybody tell me step by step how to fix that problem? I am new and I got Nvidia GeForce 1080Ti and same problem. Please Help !!!!

**Comment by lomadapraveenreddy** [comment]
can anyone help me how to solve this problem?

**Comment by PoopieFace** [comment]
I had this problem solved by updating drivers to latest.

**Comment by ashrafmoh** [comment]
Hi, I have same problem. I have Intel Hd Graphics 4000. I have Updated drivers and rebooted, but still show me the error.
Any help please !

**Comment by Grumpy-Dwarf** [comment]
Sorry only Nvidia and AMD GPUs are supported. You can mine Monero or Pascal however on your CPU with nanominer.

**Comment by ashrafmoh** [comment]
OK Thank you very much

**Comment by mhdfarouk** [comment]
hello please help me i have this issue in my  laptop 

no gpu devices were detected exiting

 attached clinfo for AMD case or output of nvidia-smi

[nvidia-smi.1.pdf](https://github.com/nanopool/nanominer/files/4714051/nvidia-smi.1.pdf)

**Comment by Grumpy-Dwarf** [comment]
@mhdfarouk You've attached nvidia-smi man page, not nvidia-smi command output.
First of all, what OS and GPU model do you have?

**Comment by mhdfarouk** [comment]
hello dear and thanks for quick reply 
as i understand what you request   kindly see below information if not right please explain  to me what you want and how i can provide u
Intel(R) HD Graphics 3000

Generic PnP Monitor

PC is  ASUSTeK Computer Inc.   N43SL

64 pit

also attached  p. screan   from  nvidia-smi 

![invidia](https://user-images.githubusercontent.com/66284069/83469658-fa4bca80-a488-11ea-84a9-93b68f2dafbd.jpg)

**Comment by Grumpy-Dwarf** [comment]
Looks like ASUS N43SL2 has NVIDIA GeForce GT 540M GPU with only 1 GB of memory. I'm not sure why it is not shown in nvidia-smi. Maybe discrete GPU is disabled while Intel GPU works. Anyway, I'm afraid this configuration is not capable to mine any Ethash or Kawpow coin on GPU because all of them need more than 1 GB of GPU memory. 2 GB at least for UBQ and new Ethash coins and 4 GB or more for ETC and ETH.
You can mine Monero or Pascal however with nanominer on your CPU. But please note laptop cooling system was not designed for such intensive tasks as mining for days.

**Comment by Ghost1805** [comment]
![image](https://user-images.githubusercontent.com/69386524/89707931-1c356200-d990-11ea-9a7f-382e84051cab.png)

**Comment by Ghost1805** [comment]
I'm getting this even after updating my drivers and rebooting my system.

**Comment by Ghost1805** [comment]
![gdhfb](https://user-images.githubusercontent.com/69386524/89708002-feb4c800-d990-11ea-813e-0992ea0981d1.png)
I've uploaded my nvidea.smi screen.

**Comment by kirsuvin** [comment]
Found a solution. After reboot without monitor plugged in, go to the device manager, enable 'show hidden devices' and remove 'intel hd graphics' with drivers. After that miner is able to detect all devices.

**Comment by rubensalves** [comment]
> Found a solution. After reboot without monitor plugged in, go to the device manager, enable 'show hidden devices' and remove 'intel hd graphics' with drivers. After that miner is able to detect all devices.
> *issue is still actual in 1.11

i tried that, but not work, thanks though. 

i using am intel uhd graphics 620
