### ISSUE TITLE
"Could not make binaries for gfx1010:xnack-"

### ISSUE THREAD

**Issue by mbana** [nanopool/nanominer#202]
## GPU Details

AMD RX 5700 XT

**Comment by T0mate** [comment]
I have the same issue.
FYI I've just update my AMD drivers to the new 21.4.1 (for windows).
I think the new drivers probably change the GPU metadata identification.

**Comment by rixxxter** [comment]
Same here after update of AMD driver to 21.4.1, I rolled back the driver of my GPU which fixed the issue

**Comment by alide123321** [comment]
Same here

**Comment by TheBrinkOfTomorrow** [comment]
Same issue here [on Linux]...  was not corrected by 3.3.5...

**Comment by T0mate** [comment]
The new version fix the issue on windows (at least for me).

**Comment by mbana** [comment]
I believe this is fixed in <https://github.com/nanopool/nanominer/releases/tag/3.3.5>. Please close.
Would be ideal or rather necessary to view the source code of this miner at some point - just saying.

**Comment by TheBrinkOfTomorrow** [comment]
> I believe this is fixed in https://github.com/nanopool/nanominer/releases/tag/3.3.5. Please close.
> Would be ideal or rather necessary to view the source code of this miner at some point - just saying.

Per my commnet above, this is not fixed on Linux [for me at least].  Have you verified it corrects the issue, or just read the release notes [which claim it's fixed]?

My experience:
./nanominer 
                                   _                 
 _ __   __ _ _ __   ___  _ __ ___ (_)_ __   ___ _ __ 
| '_ \ / _` | '_ \ / _ \| '_ ` _ \| | '_ \ / _ \ '__|
| | | | (_| | | | | (_) | | | | | | | | | |  __/ |   
|_| |_|\__,_|_| |_|\___/|_| |_| |_|_|_| |_|\___|_|   

Version 3.3.5
2021-Apr-28 18:30:05: Started EthMan server on port 3333 without a password (read-only mode).
Single device detected
GPU 0 PCI 07:00.0, Platform: OpenCL, Name: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] (gfx1010:xnack+), 8176 MB available

Ethereum last 10 min - Total: 0.000 H/s.
2021-Apr-28 18:30:06: New job from eth-us-east1.nanopool.org:9433
2021-Apr-28 18:30:06: Could not make binaries for gfx1010:xnack+
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:01

**Comment by bliekp** [comment]
Same problem here with latest nanominer 3.3.5 on Manjaro Linux, all latest packages:
xf86-video-amdgpu 19.1.0-2

**Comment by max-allan** [comment]
Same problem on 3.3.7 with latest AMD drivers (amdgpu-pro-21.10-1263777-rhel-8.3)

Single device detected
GPU 0 PCI 23:00.0, Platform: OpenCL, Name: Navi 14 [Radeon Pro W5500] (gfx1012:xnack+), 8176 MB available
-------------------Ethash:------------------
Currency: Ethereum
Wallet: 0x52ab4573b767733983f7a0ade6ef860a876a4d44
Rig name: Grumpy_154e17ba
...
Using all GPU devices
Memory tweak: 1
-------------Common parameters:-------------
Log path: ./logs/
Log is written to file
GPU watchdog is enabled
Never calling reboot.sh (always restarting the miner in case of errors).
2021-Jul-19 23:12:45: Setting up algorithm: Ethash
2021-Jul-19 23:12:46: Connecting to pools...
2021-Jul-19 23:12:46: Connected to pool: eth-eu2.nanopool.org:9433 | IP: 51.15.55.100 | ping: 83 ms.
2021-Jul-19 23:12:46: New job from eth-eu2.nanopool.org:9433 | share difficulty = 10000 MH, epoch 428 (4447 MB)
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:00
2021-Jul-19 23:12:46: Could not make binaries for gfx1012:xnack+

**Comment by sxiii** [comment]
Check out if this helps: https://gist.github.com/sxiii/a582997f49458bfc45989350f3b35601 :)

**Comment by sxiii** [comment]
Since the recent version of Fedora 35; amdgpu & nanominer, the problem is now returned:
```
Could not make binaries for gfx1012_xnack
```
