### ISSUE TITLE
Windows 11 : Hardware-accelerated GPU scheduling is not enabled

### ISSUE THREAD

**Issue by benoitfouc** [nanopool/nanominer#290]
Hi there, the miner let me this message : 
![image](https://user-images.githubusercontent.com/10956350/138276106-beef01eb-5f24-4b21-8113-7e2c1530a120.png)

But this option is activate by default : 
![image](https://user-images.githubusercontent.com/10956350/138275648-9bc25a75-cf7e-4f6f-a2c5-8a39fadb2ece.png)

I'm using others miners to mine other coins, and they are working fine.

That's probably an issue of compatibility with Windows 11 and Nanominer.
I try to mine RVN with a Nvidia GTX 1070.
I download the version of nanominer 3.3.14 CUDA11

**Comment by benoitfouc** [comment]
Fixed ! That was because i change the default disk installation on my registery, nvidia composant were not well installed.

**Comment by FabienDehopre** [comment]
@benoitfouc I have the same warning as you. Can you elaborate on how you fixed this issue?

**Comment by benoitfouc** [comment]
> @benoitfouc I have the same warning as you. Can you elaborate on how you fixed this issue?

Hello, i've fixed this issue by installing my NVIDIA drivers and software on the "default installation folder".
You can find or set this folder on your registry on HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\ProgramFilesDir 
 : https://answers.microsoft.com/en-us/windows/forum/all/how-do-you-change-the-default-installation/73450b25-d794-4f18-9add-75253b893343

let me know

**Comment by FabienDehopre** [comment]
Thanks. All my NVIDIA drivers are already installed on the default installation folder and the hardware-accelerated GPU scheduling is enabled but the warning still appears. Weird.

**Comment by LinkoMania** [comment]
I also have this problem but with my AMD Radeon RX480 card, do you have a solution?
